services:

  speedtest:
    build:
      context: .
      dockerfile: Dockerfile.speedtest
    restart: unless-stopped
    volumes:
      - data:/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - webapps_network
    deploy:
      resources:
        limits:
          memory: 200M

  dashboard:
    container_name: internet-speed-monitor-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: unless-stopped
    depends_on:
      - speedtest
    volumes:
      - data:/data:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - webapps_network
    deploy:
      resources:
        limits:
          memory: 150M

networks:
  webapps_network:

volumes:
  data:
